FOR EACH LOTE WHERE CODIGO_TRAZABILIDAD = "":

    /* ASSIGN CODIGO_TRAZABILIDAD = "". */
    DISP LENGTH(STRING(LOTE.ID_PROVEEDOR)).
    DISP (LOTE.ID_PROVEEDOR * INTEGER('1' + FILL('0',(7 - LENGTH(STRING(LOTE.ID_PROVEEDOR))) ))) FORMAT '>>>>>>>>>>>>>>'.
    /* ASSIGN  LOTE.CODIGO_TRAZABILIDAD = 'G' + STRING(LOTE.ID_PROVEEDOR * (ID_PROVEEDOR * INTEGER(1 + FILL('0',7 - LENGTH(STRING(ID_PROVEEDOR)) ))  + LOTE.ID_ORIGEN * 1000 + LOTE.ID_LOTE).*/
    /* DISP    LOTE.DESCRIPCION LOTE.ID_PROVEEDOR LOTE.CODIGO_TRAZABILIDAD. */
            
    PAUSE 0.        
END. 
 
