DEFINE VARIABLE chApp      AS COM-HANDLE     NO-UNDO.
DEFINE VARIABLE chSheet    AS COM-HANDLE     NO-UNDO.
DEFINE VARIABLE chCell     AS COM-HANDLE     NO-UNDO.

DEFINE VARIABLE cRange     AS CHARACTER      NO-UNDO.
DEFINE VARIABLE iFila      AS INTEGER        NO-UNDO.
