DEFINE INPUT PARAMETER cpuerto AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER cembalador AS CHARACTER NO-UNDO.

DEFINE STREAM sensor.    

CEMBALADOR = '0000000000'.


INPUT stream sensor from VALUE(cpuerto).
REPEAT:
    IMPORT STREAM sensor CEMBALADOR NO-ERROR.  
    IF ERROR-STATUS:ERROR  THEN NEXT.
    IF CEMBALADOR <> '0000000000' AND  cembalador <> '' THEN
        LEAVE.
END.
INPUT STREAM sensor CLOSE.
  
CATCH e AS Progress.Lang.Error.
    MESSAGE e:getmessage(1) VIEW-AS ALERT-BOX.
END CATCH.
