&ANALYZE-SUSPEND _VERSION-NUMBER AB_v10r12
&ANALYZE-RESUME
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _DEFINITIONS Procedure 
/*------------------------------------------------------------------------
    File        : 
    Purpose     :

    Syntax      :

    Description :

    Author(s)   :
    Created     :
    Notes       :
  ----------------------------------------------------------------------*/
/*          This .W file was created with the Progress AppBuilder.      */
/*----------------------------------------------------------------------*/

/* ***************************  Definitions  ************************** */

/*
DEFINE TEMP-TABLE FECHASEMANA 
       FIELD PPOSICIONDOCVENTAS AS INTEGER FORMAT 999
       FIELD PFECHASEMANA AS CHARACTER FORMAT 'X(15)'
       FIELD PCANTIDAD AS CHARACTER FORMAT 'X(15)'.

DEFINE TEMP-TABLE VAPOR 
       FIELD PPOSICIONDOCVENTAS AS INTEGER FORMAT 999
       FIELD PVAPOR AS CHARACTER FORMAT '9999'
       FIELD PDESCRIPCIONVAPOR AS CHARACTER FORMAT 'X(40)'.

       FIELD PFECHASEMANA AS CHARACTER FORMAT 'X(15)'
       FIELD PVAPOR AS CHARACTER FORMAT '9999'
       FIELD PCALIBRESTD AS CHARACTER FORMAT 'X(15)'

DEFINE TEMP-TABLE AGENCIA 
    FIELD PPOSICIONDOCVENTAS AS INTEGER FORMAT 999
    FIELD PLUGARDESCARGA AS CHARACTER FORMAT '99999'
    FIELD PAGENCIA AS CHARACTER FORMAT '99999'
    FIELD PDESCRIPCIONAGENCIA AS CHARACTER FORMAT 'X(40)'.
*/

DEFINE TEMP-TABLE POSICION 
    FIELD PORDEN     AS CHARACTER FORMAT 'x(12)'
    FIELD PFECHASEMANA AS CHARACTER FORMAT '99999999'
    FIELD PCANTIDADORDEN AS CHARACTER FORMAT 'X(16)'
    FIELD PUNIDAD   AS CHARACTER FORMAT 'X(3)'
    FIELD PMARCA  AS CHARACTER FORMAT 'X(20)'
    FIELD PCONTRAMARCA  AS CHARACTER FORMAT 'X(20)'
    FIELD PENVASE AS CHARACTER FORMAT 'X(18)'
    FIELD PESPECIE AS CHARACTER FORMAT 'X(14)'
    FIELD PVARIEDAD AS CHARACTER FORMAT 'X(14)'
    FIELD PCALIDAD AS CHARACTER FORMAT 'X(4)'
    FIELD PCATEGORIA AS CHARACTER FORMAT 'X(20)'
    FIELD PTIPOPALLET AS CHARACTER FORMAT 'X(20)'
    FIELD PTIPOESQUINERO AS CHARACTER FORMAT 'X(20)'
    FIELD PMERCADO AS CHARACTER FORMAT 'X(10)'.

DEFINE TEMP-TABLE TCALIBRE 
       FIELD PCALIBRESTD AS CHARACTER FORMAT 'X(15)'
       FIELD PCANTIDAD AS CHARACTER FORMAT 'X(13)'.

DEFINE TEMP-TABLE TVAPOR 
    FIELD PVAPOR AS CHARACTER FORMAT '9999'
    FIELD PDESCRIPCIONVAPOR AS CHARACTER FORMAT 'X(40)'.
    
DEFINE TEMP-TABLE TAGENCIA
    FIELD PLUGARDESCARGA AS CHARACTER FORMAT '99999'
    FIELD PAGENCIA AS CHARACTER FORMAT '99999'
    FIELD PDESCRIPCIONAGENCIA AS CHARACTER FORMAT 'X(40)'.

DEFINE TEMP-TABLE CABECERA
    FIELD SDOCUMENTOVENTA AS CHARACTER FORMAT 'X(10)'
    FIELD SPOSICIONDOCUMENTOVENTA AS CHARACTER FORMAT '999999'
    FIELD SSOLICITANTE AS CHARACTER FORMAT 'X(10)'
    FIELD SNOMBRE AS CHARACTER FORMAT 'X(30)'
    FIELD SFECHADOCUMENTO AS CHARACTER FORMAT '99999999'
    FIELD SMATERIAL AS CHARACTER FORMAT 'X(18)'
    FIELD SCANTIDAD AS CHARACTER FORMAT '99999999'
    FIELD SUNIDAD AS CHARACTER FORMAT 'X(3)'
    FIELD SPUERTOSALIDA AS CHARACTER FORMAT '99999'
    FIELD SDESCRIPCIONPUERTOSALIDA AS CHARACTER FORMAT 'X(40)'
    FIELD SDESTINO AS CHARACTER FORMAT '99999'
    FIELD SDESCRIPCIONDESTINO AS CHARACTER FORMAT 'X(40)'
    FIELD SPUERTOLLEGADA AS CHARACTER FORMAT '99999' 
    FIELD SDESCRIPCIONPUERTOLLEGADA AS CHARACTER FORMAT 'X(40)'.


DEFINE TEMP-TABLE CABECERA-TEMPORAL
    FIELD SERIE AS INTEGER
    FIELD SORDEN AS CHARACTER FORMAT 'X(12)' 
    FIELD SDOCUMENTOVENTA AS CHARACTER FORMAT 'X(10)' 
    FIELD SSOLICITANTE AS CHARACTER FORMAT 'X(10)' 
    FIELD SNOMBRE AS CHARACTER FORMAT 'X(30)' 
    FIELD SPOSICIONDOCUMENTOVENTA AS CHARACTER FORMAT '999999' 
    FIELD SMATERIAL AS CHARACTER FORMAT 'X(18)' 
    FIELD SESPECIE AS CHARACTER FORMAT 'X(14)' 
    FIELD SVARIEDAD AS CHARACTER FORMAT 'X(14)' 
    FIELD SCANTIDAD AS CHARACTER FORMAT '99999999' 
    FIELD SUNIDAD AS CHARACTER FORMAT 'X(3)' 
    FIELD SCALIDAD AS CHARACTER FORMAT 'X(4)' 
    FIELD SCATEGORIA AS CHARACTER FORMAT 'X(20)' 
    FIELD STIPOPALLET AS CHARACTER FORMAT 'X(20)' 
    FIELD STIPOESQUINERO AS CHARACTER FORMAT 'X(20)' 
    FIELD SPUERTOLLEGADA AS CHARACTER FORMAT '99999' 
    FIELD SDESCRIPCIONPUERTOLLEGADA AS CHARACTER FORMAT 'X(40)' 
    FIELD SDESTINO AS CHARACTER FORMAT '99999' 
    FIELD SDESCRIPCIONDESTINO AS CHARACTER FORMAT 'X(40)' 
    FIELD SFECHADOCUMENTO AS CHARACTER FORMAT '99/99/9999'
    FIELD SVAPOR AS CHARACTER FORMAT '9999' 
    FIELD SDESCRIPCIONVAPOR AS CHARACTER FORMAT 'X(40)' 
    FIELD SLUGARDESCARGA AS CHARACTER FORMAT '99999' 
    FIELD SPUERTOSALIDA AS CHARACTER FORMAT '99999' 
    FIELD SDESCRIPCIONPUERTOORIGEN AS CHARACTER FORMAT 'X(40)' 
    FIELD SMERCADO AS CHARACTER FORMAT 'X(120)' 
    FIELD SCONTRAMARCA AS CHARACTER FORMAT 'X(20)' 
    FIELD SAGENCIA AS CHARACTER FORMAT '99999' 
    FIELD SDESCRIPCIONAGENCIA AS CHARACTER FORMAT 'X(40)'
    FIELD SMARCA              AS CHARACTER FORMAT 'X(20)' . 



DEFINE TEMP-TABLE POSICION-TEMPORAL
    FIELD SERIE AS INTEGER
    FIELD PDOCVENTAS AS CHARACTER FORMAT 'X(15)'
    FIELD PPOSICIONDOCVENTAS AS CHARACTER FORMAT '999999'
    FIELD PMATERIAL AS CHARACTER FORMAT 'X(18)'
    FIELD PENVASE AS CHARACTER FORMAT 'X(18)'
    FIELD PCALIBRESTD AS CHARACTER FORMAT 'X(15)'
    FIELD PCALIBREEQU AS CHARACTER FORMAT 'X(15)'
    FIELD PCANTIDAD AS CHARACTER FORMAT 'X(15)'
    FIELD PUNIDAD AS CHARACTER FORMAT 'X(3)'
    FIELD PORDER AS CHARACTER FORMAT 'X(12)'.

DEFINE TEMP-TABLE CALIBRE-TEMPORAL
    FIELD PCALIBRE AS CHARACTER   FORMAT 'X(10)'
    FIELD PPORCENTAJE AS DECIMAL.

DEFINE TEMP-TABLE RESPUESTA NO-UNDO
    FIELD POSTATUS  AS CHARACTER INITIAL 'OK'
    FIELD POMENSAJE AS CHARACTER.

    
DEFINE DATASET DREQUEST FOR CABECERA,POSICION,TCALIBRE,TVAPOR,TAGENCIA.




DEFINE INPUT PARAMETER DATASET  FOR DREQUEST.
DEFINE OUTPUT PARAMETER TABLE FOR RESPUESTA.

DEFINE VAR I AS INTEGER NO-UNDO.
DEFINE VAR ILUG AS INTEGER NO-UNDO.
DEFINE VAR IPUERTO AS INTEGER NO-UNDO.
DEFINE VAR ICLIENTE AS INTEGER NO-UNDO.
DEFINE VAR IORDEN AS INTEGER NO-UNDO.
DEFINE VAR CDESTINO AS CHARACTER NO-UNDO.
DEFINE VAR CTIPOESQUINERO AS CHARACTER NO-UNDO.
DEFINE VAR CESPECIE AS CHARACTER NO-UNDO.



DEFINE VAR FLAG-ESQUINERO AS LOGICAL NO-UNDO.
DEFINE VAR ISERIE AS INTEGER NO-UNDO.
DEFINE VAR iITEM AS INTEGER NO-UNDO.

DEFINE VAR ICALIDAD AS INTEGER NO-UNDO.
DEFINE VAR CVARIEDAD AS CHARACTER NO-UNDO.
DEFINE VAR CENVASE AS CHARACTER NO-UNDO.
DEFINE VAR CMARCA AS CHARACTER NO-UNDO.
DEFINE VAR IPALETIZADO AS INTEGER NO-UNDO.
DEFINE VAR CTIPOPALET AS CHARACTER NO-UNDO.
DEFINE VAR CCATEGORIA AS CHARACTER NO-UNDO.
DEFINE VAR ITRATAMIENTO AS INTEGER NO-UNDO.
DEFINE VAR CVAPOR AS CHARACTER NO-UNDO.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


&ANALYZE-SUSPEND _UIB-PREPROCESSOR-BLOCK 

/* ********************  Preprocessor Definitions  ******************** */

&Scoped-define PROCEDURE-TYPE Procedure
&Scoped-define DB-AWARE no



/* _UIB-PREPROCESSOR-BLOCK-END */
&ANALYZE-RESUME



/* *********************** Procedure Settings ************************ */

&ANALYZE-SUSPEND _PROCEDURE-SETTINGS
/* Settings for THIS-PROCEDURE
   Type: Procedure
   Allow: 
   Frames: 0
   Add Fields to: Neither
   Other Settings: CODE-ONLY COMPILE
 */
&ANALYZE-RESUME _END-PROCEDURE-SETTINGS

/* *************************  Create Window  ************************** */

&ANALYZE-SUSPEND _CREATE-WINDOW
/* DESIGN Window definition (used by the UIB) 
  CREATE WINDOW Procedure ASSIGN
         HEIGHT             = 15
         WIDTH              = 60.
/* END WINDOW DEFINITION */
                                                                        */
&ANALYZE-RESUME

 


&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _MAIN-BLOCK Procedure 


/* ***************************  Main Block  *************************** */
FIND FIRST CABECERA.
MESSAGE CABECERA.SCANTIDAD VIEW-AS ALERT-BOX.
RUN CREATABLACALIBRES.
RUN CREATABLATEMPORAL.

CREATE RESPUESTA.
RESPUESTA.POSTATUS = 'OK'.
RESPUESTA.POMENSAJE = ''.

FOR EACH CABECERA-TEMPORAL.
/*    RUN CREAPOSICIONES. */
    RUN ORDPROD.P (
    CABECERA-TEMPORAL.SORDEN, CABECERA-TEMPORAL.SDOCUMENTOVENTA, CABECERA-TEMPORAL.SSOLICITANTE,
    CABECERA-TEMPORAL.SNOMBRE, CABECERA-TEMPORAL.SPOSICIONDOCUMENTOVENTA, CABECERA-TEMPORAL.SMATERIAL,
    CABECERA-TEMPORAL.SESPECIE, CABECERA-TEMPORAL.SVARIEDAD, CABECERA-TEMPORAL.SCATEGORIA,
    CABECERA-TEMPORAL.SUNIDAD,CABECERA-TEMPORAL.SCALIDAD,CABECERA-TEMPORAL.SCATEGORIA,
    CABECERA-TEMPORAL.STIPOPALLET,CABECERA-TEMPORAL.STIPOESQUINERO,CABECERA-TEMPORAL.SPUERTOLLEGADA,
    CABECERA-TEMPORAL.SDESCRIPCIONPUERTOLLEGADA,CABECERA-TEMPORAL.SDESTINO,CABECERA-TEMPORAL.SDESCRIPCIONDESTINO,
    CABECERA-TEMPORAL.SFECHADOCUMENTO,CABECERA-TEMPORAL.SVAPOR,CABECERA-TEMPORAL.SDESCRIPCIONVAPOR, 
    CABECERA-TEMPORAL.SLUGARDESCARGA, CABECERA-TEMPORAL.SPUERTOSALIDA,CABECERA-TEMPORAL.SDESCRIPCIONPUERTOORIGEN,
    CABECERA-TEMPORAL.SMERCADO, CABECERA-TEMPORAL.SCONTRAMARCA,CABECERA-TEMPORAL.SAGENCIA,
    CABECERA-TEMPORAL.SDESCRIPCIONAGENCIA, CABECERA-TEMPORAL.SMARCA, INPUT TABLE POSICION-TEMPORAL) NO-ERROR.
    
    IF ERROR-STATUS:ERROR THEN
    DO:
        RESPUESTA.POSTATUS = 'NOK'.
        RESPUESTA.POMENSAJE = RESPUESTA.POMENSAJE + 'ORDEN: ' + STRING(CABECERA-TEMPORAL.SORDEN) + '-' + ERROR-STATUS:GET-MESSAGE (1) + '|'.        
    END. 
    IF RETURN-VALUE <> 'OK' THEN
    DO:
        RESPUESTA.POSTATUS = 'NOK'.
        RESPUESTA.POMENSAJE = RESPUESTA.POMENSAJE + 'ORDEN: ' + STRING(CABECERA-TEMPORAL.SORDEN) + '-'  + RETURN-VALUE + '|'.        
    END.        
END.
RETURN.

/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME


/* **********************  Internal Procedures  *********************** */

PROCEDURE CREATABLACALIBRES.
    DEFINE VAR TOTALC AS DECIMAL.
    DEFINE VAR TOTALD AS DECIMAL.
    

    FOR EACH TCALIBRE.
        MESSAGE TCALIBRE.PCALIBRESTD VIEW-AS ALERT-BOX.
        
        TOTALC = TOTALC + DECIMAL(TCALIBRE.PCANTIDAD).
    END.
    FOR EACH TCALIBRE.
        CREATE CALIBRE-TEMPORAL.
        ASSIGN CALIBRE-TEMPORAL.PCALIBRE = TCALIBRE.PCALIBRESTD
               CALIBRE-TEMPORAL.PPORCENTAJE = ROUND(DECIMAL(TCALIBRE.PCANTIDAD) / TOTALC, 2).
        TOTALD = TOTALD + CALIBRE-TEMPORAL.PPORCENTAJE.
        MESSAGE TOTALD .
    END.
    FIND LAST TCALIBRE.
    CALIBRE-TEMPORAL.PPORCENTAJE = CALIBRE-TEMPORAL.PPORCENTAJE + TOTALC - TOTALD.
    MESSAGE 'ACA' .
END PROCEDURE.


PROCEDURE CREATABLATEMPORAL.
    ISERIE = 0.
    FOR EACH POSICION.
        ISERIE = ISERIE + 1.
        
        FIND FIRST TVAPOR NO-ERROR.
        FIND FIRST TAGENCIA NO-ERROR.
        
        {findcabecera_1.i}
        IF NOT AVAILABLE CABECERA-TEMPORAL THEN
        DO:
            CREATE CABECERA-TEMPORAL.
            {assigncabecera_1.i}
        END.
        FOR EACH TCALIBRE.
            {findposicion_1.i}
            IF NOT AVAILABLE POSICION-TEMPORAL THEN
            DO:
                CREATE POSICION-TEMPORAL.
                {assignposicion_1.i}
            END.
            POSICION-TEMPORAL.PCANTIDAD = POSICION-TEMPORAL.PCANTIDAD + TCALIBRE.PCANTIDAD.
        END.
    END.
 
END PROCEDURE.

FUNCTION WLOG RETURNS LOGICAL (INPUT ARCHIVO AS CHARACTER, INPUT TEXTO AS CHARACTER):
    OUTPUT TO VALUE(ARCHIVO) APPEND.
    EXPORT DELIMITER "|" STRING(NOW)  TEXTO.
    OUTPUT CLOSE.
    RETURN TRUE.
END FUNCTION. 